### ISSUE TITLE
Random values on relational resources won't work

### ISSUE THREAD

**Issue by hrenard** [python-scim/scim2-tester#10]
https://github.com/yaal-coop/scim2-tester/blob/410bafadf24427260440f7f723ed43ff7ed1afaa/scim2_tester/resource.py#L215
This works for standalone resources but not for resources containing relations. 
For instance, a group will contain members that don't exist, and it will lead to an error response from the service provider.

**Comment by azmeuk** [comment]
This have been fixed by e641f4dfb77729df4d1b2df00f40466596e6ca13, and the reference tests will be properly handled later with #15.
